workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 10
    environment:
      android:
        sdk: 30
    scripts:
      - echo "Starting build..."
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - you@example.com
